name: Run Node Cron

on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Debug structure
        run: ls -R

      - name: Create cookies.json
        run: |
          cat <<EOF > cookies.json
          ${{ secrets.COOKIES_JSON }}
          EOF

      - name: Run script
        run: npm install && node index.js